#+TITLE: ssss
#+AUTHOR: snekism
#+LANGUAGE: fr
#+EXPORT_FILE_NAME: index.html
#+HTML_HEAD: <link rel="stylesheet" href="https://sandyuraz.com/styles/org.min.css">


* starting a mind blog

  instead of venting on reddit and IRC and feel abusing others ears
  and eyes, I should publish online. Whoever feels worth spending time
  on these words can do it without me feeling like a self absorbed
  asshole much. I believe writing helps a lot, better thinking,
  diffusing negative emotions.. so I'm gonna do it a bit.

* state of mind @ Sat 30 Jan 2021 09:34:57 AM CET

  I went to a job interview, I was anxious, didn't want to go. It
  failed due to misunderstandings but I felt almost happy for a
  minute.

  What made this ? having a place to go every day ? belonging to a
  group ? being around toys to play with ? (in that case cars).

* i'm tired, my age and mindset relationship

  i have a diploma, some skills, some motivation but at the same time
  I start to not give a fuck about all this. I don't want to chase
  performance, as if my ego is gone. I don't want money much. I want
  stability.. but that may be due to fatigue and lack of control.
  Also I want respect and honest appreciation. I work fast and hard
  whenever I can. I never stop, never waste time. People are slow,
  ranty, unmotivated, or maybe they simply appreciate life
  differently. Maybe my brain is hyperanxious and need stimulation all
  the time. Maybe I don't care about these people and want to drown in
  action to feel happy. A blend of all this.

* github.io activated

  spent 10 minutes setting up github as host for this.  felt real
  boring but alas.. I wonder if people are paid for these tasks
  sometimes, probably. Not important.

* situations at the house not better

  father is really overwhelming, cranky and heavy.. the more a
  situation goes bad, the worst he becomes. Tension makes him more
  tense. Nothing surprising.

  My mother talks about him as a thing. In front of me.. makes me mad.

  It's still a rotting pot of anger. You know where every move sounds
  angry. A door close for no reason, a drawer shut too fast. Dishes
  dropped loudly.

  I should write a note and leave. If I wasn't afraid my parents
  wouldn't go violent I'd do so. I guess that's exactly the problem in
  these kind of situations.. you don't move because it's a lose-lose
  situation with potentially critical consequences.

  Maybe I should talk to people and find support.

* work - volunteering

  I like volunteering at the food charity. My tasks are basic. The
  rhythm is average. People are not in a rush either.  Some would say
  they're a charity so obviously they're not in a hurry, but truth is
  that most private places I went to weren't faster. Only people
  dealing with high rates of clients (restaurants, trains) have hard
  rhythm constraints. Oh and high production rate factories. But I
  like that.. I don't know why people hate going fast on repetitive
  gestures. To me it's like converging toward perfection and then
  keeping there for 4 hours. A high zen experience. I'd understand for
  physical labour done wrong.. nobody wants to carry 10 tons of stuff
  for 4 hours. But even unpacking lots of food can be fun. You just
  have to organize yourself to find the easiest and fastest
  configuration. Then it becomes a pleasure. Truth is people don't do
  this because 1) education (as a programmer I became used to seek
  every wasted second) 2) petty revenge due to feud with hierarchy or
  other people. Why work fast if your boss talks down to
  you.. respect/care/affection is such a big factor in how we work. A
  good king could make a whole nation work twice better just by his
  appreciation only.

* redinho waste

  https://completemusicupdate.com/wp-content/uploads/2017/10/tomcalvertzanbor1250.jpg

  | https://imgur.com/a/u9ZhXeZ  |
  |------------------------------|
  | https://archive.is/wip/hamjV |

  see this pic. a busted synth.. parts out in the open, internals
  exposed, design off.

  that thing was an epic item in the 90s, high valued device or toy,
  for a high valued art form gone semi-mainstream.

  but it was fabricated.. yet it's not what it was important for, it's
  that glow from how it looks and convey it's use and
  capabilities. how you feel and interact with it. how it embodies the
  desires and factors of an era.

  something that I consider timeless and more important than the
  current thinking about innovation. especially the immaterial side of
  new tech.

* phases and big picture

  few years earlier i was a slacker, illegal streaming and porn was my
  daily life, sleeping the day.. life felt like shit but nothing near
  close to how heavy, difficult and painful it is now. The irony is
  that I do 100x more..



* era of simulacre

  we're being sold that more data, more pics, more pixels is
  better. these were side bonuses of a good life, having good times
  and enough more to buy a camera, but the camera means nothing. old
  fading 70s pics, blurry pics .. photo albums with 10 .. have more
  worth than my google photo account filled with 1000s of superb (not
  really) shots of my lonely sad self.

* inotify upload

  ```inotifywait -q -m -e CLOSE_WRITE --format="git commit -m 'auto
  commit' %w && git push origin <<branch>>" <<file>> | bash```

* to drop or not to drop

  Apres la tension et la douleur des derniers jours, je me sens
  vide. J'ai plus la reponse anxieuse qui me fait vouloir
  lutter.. j'abandonne mes parents a leur misere et je vais finir ma
  vie tristement un peu plus loin.

  La culpabilite me detruit toujours. Et c'est normal.

  Suis-je le seul responsable..

  --


* recovery

  is it possible I recover to a normal state of existence ? my
  childhood feels dead, I have no people around I love, only ghosts
  with whom I have painful feelings, who are hurting me a lot, who
  never made me feel me .. nobody knows me. not surprising, I couldn't
  speak before, but now I do nobody listens. it's horrible, my truth,
  my soul is dust in the wind.

* trading sucks and doesn't

  trading is a soulless game where someone gives you his money so he
  can wait to later be in profit or not.

  most of the trading is superstitiously weak science (averages
  averages averages fib series averages)

  but it has some general life lessons:

  - follow others for a while
    benefits are easier

  - don't follow others (sic)
    when they go insane. the system lives on the mean. that's where
    things are stable

  - be patient
    timing is key, too early you lose, too late you lose

  - be cautious
    you lose if you stop prepping for problems

  - cycles everywhere

  - learn how to get into chaos without being foolish

    you have to tame fear, thus design plans to deal with all outcomes

  -

* sour pain, deep and wide, silence

  i want to leave 'these persons' away.. i only feel happy when I
  picture myself with others, I have remains of life in me, but I
  can't express it with them.

  part of it is the years of sadness in this house

  part of it is the guilt of my maybe crime

  part of it is .. i forgot. I shouldn't be editing text while I
  listen to aerosmith.

  since my breakup I have this feeling that interacting with people is
  different, i need to be heard, i need genuine contact and honesty
  and connection

  it's a critical need

  and every time I talk to my parents.. there's no such things, it's
  fake, twisted, or silence

  that's why I want them out.

  they provided a roof.. but I can make a roof, it's not what I need

  I scream in my head since i'm in college, nightmares and now pure
  pain.

  future looks bleak, i'm thinking of offing myself because I can't
  deal with more grief, i cant kill them from my head either tbh.. but
  it doesn't evolve well

  I assume that's what people feel when marriage/couple doesn't work
  and the other party cannot listen or make an effort.

  Sometimes I want to scream, sing, make music to let the pain out,
  the life out. But if feels so weak and so worthless now..

  even anger or breaking things seems moot, I felt utterly defeated at
  the store today.. a whole 20 years of life gone. vapor. Actually
  that's a cute image. Even this whole failure is not nothing.. it
  became vapor.

  it's like i never lived, my impulses are gone, my desires are gone,
  there's no blood

  yet i have this void and this need to have some.. to have been

  it hurts.

  This is why I want to harm my mother(and father too) I think somehow
  they deprived me of that. They never wanted to see me alive.. any
  time I try I get shit or hurdles from them.

  falling on your face is bliss

  it mean you tried

* dignity and life

  forgot.

* irc

  175

  <snek76`> damn I had to drop my mother at the car shop [18:24] |
<snek76`> every second next to her is a death sentence of anxiety |
<snek76`> "i need to leave" | <snek76`> she exudes stress nearby her
own son | <snek76`> she claim she 'loves' me all the fuckin time |
<snek76`> but she uses me as a prop | <snek76`> makes me very violent
[18:25] | ERC>


* elders

  most of my mother family is annoying, sad, sick.

  not interesting, rambling, judging, drinking

  I want to tell them to go fuck off

  But I feel dirty. I think I can't disrespect them. I think it's
  sacred. Roots you shall not break.

* life

  why am i stuck ? cause I didn't have the possibilty of living. I
  couldn't make friends, i faked my existence mostly .. it ended
  nowhere

  then i had that girl it was eye opening.. but i lost her

  and even though i could work, i always could since i was a 6yo..

  i need friends, human relationships .. not contractual ones for
  money

  i dont want to perform, to get customers.. it's devoid of meaning
  and makes me suicidal at times

  i help for free at the charity.. free. i don't care about money

  people never hear me, never listen, never understand..


* importance

  some stuff have more value than others

  i'm 40. i try not to mind about the figure but it's dramatic, i feel
  in pain most of my time, memories are fading, and these are actually
  the only thing I care about.. anything 'good' I can do now is mostly
  damage control / me-too revenge. I don't care about being successful
  or making money, I'd rejoy a lot more in the warmth of old friends
  and family but i broke that.

  maybe i over analyze my role into this but still if our lives were
  driven around preserving these I think a lot of us would be happier.

  I see tearful eyes when I ran into people I knew. They miss the days
  too.. they walk with the burden of the void.

* self talk

  I ramble about me all the time

* reconnect forget forgive confess

  can i reconnect with people around ?

  without telling the truth ?

  i don't think so

  it's a lose lose situation

* when you can't cry anymore

  Confused and painful life to that point is hard to deal. it's a sad
  kind of grief.

  I wasn't able to live before, and i messed up, and now i'm guilty
  and i can 'live' but i'm guilty so I cannot life in joy and peace
  because morally it's wrong, and morales and humanity is exactly what
  I just got.

  I despise.. or hate people that were around me at the time. They
  didn't help.. are you responsible.. not really. But I expect them to
  blame me fully when they'll know. Unfair. I wasn't capable of
  dealing with these things. Honestly something was not there in my
  brain. Oh well I could have but I was weak.. having a gf and feeling
  love just made me stronger and opened my eyes to responsibilty.

  I'll have to confess. I'll die because of it but I'll die human.

* shrink limits - hate - grief

  new therapist is talkative, it helps a lot for me, silence is not
  what i need, there's plenty of silence in my own room or car.

  i cannot discuss everything i really need to, she still thinks
  moving out is the best course of action.. it's a delicate matter.

  moving signals this family is officially sick. my desire was to have
  just enough time to find a simple job, live a bit, find a
  flat.. evolve swiftly but organically.

  parents are not letting this happen

  now with that therapist i am a bit neutral but whenever i'm home i
  become sad and suffering again.


* ground to nothing

  i lived 30 years following others, accepting in secret what i didn't
  want to

  this girl unlocked my self esteem

  but also made me subject to deep wounds whenever people did
  something wrong in my views

  to avoid harming others with verbal rage i .. killed myself

  i hate most people around me

  they're weak, lame, sad, liars, abusers, rapists, fake, ignorants,
  limited, dishonest

  i want them all of my sight.. well i wanted, i should have send them
  to fuck off clearly, just so once in my life, when i need to exist,
  to have my voice and my soul heard out loud and clear

  i didnt

  and now this energy of life left me

  i left my own body.

  it feels like a bruise in my brain, not even trying to paint a
  picture, it does actually hurt(something odd since brain has no
  nociception in theory)

  in a way i would have hurt some people physically because i hate
  them so much

  but i would have been free and alive I assume.

  it's difficult to deal with so many extinctions of the self.

* blips of joy

  i'm still guilty, still angry, still violent, still hateful

  want to get rid of everybody in my head

  yet 5 minutes ago I had that feeling of friendship and people i used
  to know with a good 'hi friend what are you doing ?' with a normal
  feeling of affection and fun.

  i don't know what's what.. i don't know what to feel or trust.

  so weird

  I want to cry because I feel nothing or don't love my relatives.

  maybe i'm still fucked up from grieving.

  but everytime my mother closes a door, or talks about death

  the suffering comes back

  i hate her

  i hate her fucked up brain u_u;


  ... even writing this is useless, but I guess I cannot be heard nor
  taken into account. They're all wrong and they're killing me without
  caring. Shrink thinks I should talk to them more but why.. they
  never understand, and keep doing it. hhhaa

* what to do.

  I keep having memories of 'friends' i somehow hate.  Two things, I
  wasn't happy at that time, and I did them wrong.  The childhood
  memory that would have been a reason to forgive and evolve with them
  a bit, as normal friend would do, is bruised and painful like my ex
  memories. Since I had to kill her from my head.. I can kill anybody
  from my head that makes me suffer.  It's inhuman.

  Same for my parents, they're here but we don't talk.. I want to fix
  the situation in theory.. but these are not my 'parents'.. these are
  people that used to be my parents. People that would be somehow
  empathetic to me.. I'm not screaming to my needs only, even when I
  try to do good for all of us.. they cause me pain.

  I should confess.. but it's a terminal loss loss situation.

  Maybe I should consult a doctor.

  oh, and right now I'm making money on speculation, i'm literally a
  cliché of the sad guy. +1 cents every day, and -1 friend every
  day. No balance.


* death

  they ignored my suffering when i was silent

  they ignored my suffering when i was vocal

  they ignored my wounds, my injuries and made me suffer more for
  their petty needs

  supporting their manias or violence, my mother going insane over
  details on her mother's grave

  they harm me emotionally on a regular basis

  sometime they even claim they want to forget me

  i was doing great things, recovering cleanly, working nicely, being
  healthy

* reality is relative to short / long term understanding

  kinda like .. spacetime.. every local spot has its own reality due
  to ignorance of further away what's "happens" in the near time has
  no real bearing on what is true or real things that are true now may
  just appear true because they hold

  due to whatever temporary reasons

  even though quite later they'll fail and be replaced by the opposite

* depression is void of emotional memory

  you remember good
  you want more
  you happy
  you go for the same good things again

  depression robs this ?

  the memory isn't there, is contradicted by other memories

  you have nothing to seek

  @see-lower: friendship also responds to this principle. other people
  share, represent, incarnate, revives these memories. keep that
  something alive

* like a stranger

  i look at my father, his family, his life, the music

  the memories

  they're faded but not sour.. not grief. yet my father is still there
  but it's in me.

  I'm a bit sad it's over, it was nice in a way.

  we can't talk.. we never did. i wonder if he's hurt by the silence,
  the pain..

  i don't want to break it further.. i'll find a job,

  i would already have done so if my parents weren't so
  difficult.. but i'll make more steps.

  i cannot violate this.


* internet is too much self

  we spend too much writing about our own thoughts but not in the same
  way ? maybe reflection is not made to be written for 1000s to see.

  maybe chatting with others is not about your deep thoughts but about
  fun times...

  so many people are into self businesses.. at home studio, at home
  craft. I do understand some of it though.. depending on others or
  working with others can be tremendously difficult if not harmful.

* father playing zouk

  songs of my childhood, it all hurts us when this past goes away, the
  memories are weak.. people aren't there.

  that girl represented the transition to me, i'd have made her visit
  my childhood, hers too, we'd make babies.. my parents would see a
  new branch of life, newborn happiness to catter to.

  and it all went away.

  people had this, they had girlfriends, they brought them to the
  place they loved, they lived, they shared ..

  i did not

  it was important

* focusing on what to fix

  can i fix my life ?

  can i fix my mistakes ?

  one, probably not

  what about the rest:

  - no social life
  - immense regrets
  - lost past
  - dead parental relationship with very sour feelings
  - dying sense of self
  - dying sense of purpose
  - dying connection to the values of this era
    why cant i exist with the values i hold
    why am i stuck in a pit when most people dont do as much, as good

  - health: diet ok, sport restarted yesterday.

* psychiatric ego destruction

  learning how it felt to love someone that deep, and losing that .. charred my brain

  I had to willingly forget, let go, erase someone important to my existence away

  anybody making me feel bad, unloved, has the same effect.. I want them away from my soul.

* parents fous

  ma mere ne me parle que pour me guilt trip avec des choses sales

  tristes, angoissantes, bidons..

  j'ai jamais pu parler, et maintenant que je peux elle ne se sert de sa parole que
  pour me fatiguer ou me blesser

  je la hais infiniment

  une toute petite part de moi l'aime encore du lien filial mais grossomodo je pense
  que je risque sa vie si je passe du temps avec elle.

  pareil pour mon pere

  leur relation morte n'a laisse que de la merde dans mon coeur

* je hais ce monde faux et mediocre

  mais suis-je meilleur..

  tout ce que je vois de beau est neglige par le monde

  tout ce que je vois de faux est encense par des bidons

* ma mere

  aspi en panne, aller-retour a des magasins pour en acheter un autre

  ma mere conchie sur les vendeuses, tourne en rond enervee pour rien

  hesite sur tout

  s'arrete sur des trucs debile

  j'ai la haine mais j'me dis qu'elle craque, qu'elle est encore en depression

  mais la j'en ai juste marre en fait

  elle est peut etre en train de crever, mais elle dira jamais rien

  elle va te le faire payer indirectement

  et j'en peux plus.

  en plus elle fait rien pour evoluer, si on lui parle elle devie ou nie

  j'ai pas confiance, et sa mort me pousser a la mienne

* suicide is not death but the opposite

  i suffer a great deal from too much loss

  i could avoid pain by wiping my memory, moving away, becoming someone else
  but the loss, pain .. is what defines who i was and still am

  it's unbearable at times, overbearing often .. which makes having suicidal ideations

  but I'd rather kill myself to exist after wiping my self mentally, suicide is to preserve
  what's left of my identity even in an inanimte form.

* her

  she saw my look, i cared about her but the physical side wasn't really working
  the friendship was too frail

  it all broke

  it's still my most precious feeling but i can't restore it

  all my life is like this now, family: gone, friends: gone, ego: gone

  tough

* I have no voice any more

  two years ago I had slight desires: music, writing, sport, work

  parents destroyed what was left.. I don't feel much these days

  I don't want to sing, to speak, to scream .. neurologically it would be worth researching.

  As a patient though I want it to end.. it's not pretty.

* a chat [with the mother]

  mother tried to talk to me

  after babbling about useless topics she asked about what I did today, talked about work

  she sees me as a problem to manage, and it makes me go into complain mode (because now I have zero energy
  after all the tension and bs at home). 2 years ago I had drive and almost joy but she contributed
  to destroy it... of course now I'm weak and I cant tolerate assholes at a job, i want something stupid
  to forget about life

  it's.. exhausting but at least it was a slightly more honest talk, a change for once

  that said her behavior still irks me (letting her self go, smoking)

  .. to be continued.

* j'aime pas ce que j'ai fait de ma vie

  peut-etre c'est une realisation normale, je me rappelle mon rapport a la vie courante
  les magasins, les catalogues. .. les choses simples
  c'etait assez merveilleux en soit

  mes etudes, mes pseudos ambitions, mes echecs, mes erreurs .. j'ai perdu le sens des realites

  enfin si j'avais pas rate ma relation a la con la .. 

* hn reply Tue 23 Mar 2021 02:02:37 AM CET

> I relate to this deeply as a creative person. I'm in the middle of trying to bootstrap some businesses this year, and the act of creating these things is such torture sometimes.

Which is weird right? I've left my day job, I'm doing exactly what I want to do, working on exactly what I want to work on, so it should be great all the time right? And yet the daily emotional sensations I feel while actually doing the work is usually a mixed bag. Every once in a while I'll have a fantastic day where I feel great about what I'm doing from start to finish, but sometimes just defeating the resistance within me and getting any trivial amount of work done is the best I can do.

A lot of it comes down to basic quality of many creative endeavors: starting is easy, and finishing is hard. You can start anything, but if you work for long enough eventually you arrive at this ugly middle place. The part of the journey where you start to notice all the warts and imperfections of what you're making, when your limits start to show themselves, when the picture of the thing in your mind starts to diverge from what you're realistically capable of doing. Seeing that, knowing that it was you who created all of that "crap," and _still_ pushing through it to get to the flawed, imperfect, compromised final product, THAT is tough.

I suspect this is what Adams was expressing: "Arthur Dent is a burk. He does not interest me." Or expressed differently: "This character I've created is starting to become ugly in his imperfections, and I feel like I'd rather throw the work away than continue with it."

If you're curious to read more, I write about these kinds of ideas in this part of a recent blog I wrote: https://startupinamonth.net/month-two-week-three/#flying-on-...! 

---

I have a feeling that all of this, and it's not uncommon, comes from a youthful naive vision of what life should be about, based on childhood and teen years.. basically deep inspiration bouts.

A lot of people, especially in this era, want to pursue passions, a deep art they feel strongly about, even if they have a solid job already. But quite often they end up recreating a boring job .. because adult life is about regularity in the context of others needs. Nobody will care if you can deliver the ultimate standup punchline once in the year that all your peers will bow before. All that matters is that you fill the theater 5 days a week with a regular level of quality that appeal to a large enough crowd. With time the art fades behind the business, you'll use the same tricks you know work.

* degrowth

ca va faire dans le pathos

apres ma premiere relation, j'ai decouvert des emotions que je connaissais pas

je parle pas d'etre amoureux, je parle de la joie d'exister, de s'aimer et d'aimer les autres

d'etre proche physiquement et emotionellement, regarder les gens dans les yeux et rire avec eux vraiment

le besoin de lien humain sincere et profond

un truc que j'ai pas eu je crois

puis un manque de renouer avec les gens important de facon propre

manque de bol la rupture et les annees suivantes ont detruit la majeure partie de ce moi nouveau

et c'est un sombre chaos dans ma tete la..

je ne pleure plus mon enfance, ma famille .. plus rien, mon coeur est vide alors qu'il venait de reprendre vie

je suis limite en post-traumatisme la, le moindre blabla non sincere me lance des douleurs dans le corps, les gens manipulateurs, la froideur, la betise ou le vice..

j'ai envie de hurler mais rien ne sort puis la pulsion meurt elle aussi et moi un peu par la meme occasion

y'a 2 ans j'avais de la vie en moi, de la vigueur, de la saine colere face aux mediocrites ambiante et la pulsion d'aller vers mon mieux et en jouir, c'est parti.. les psys ne realisent pas a quel point cet aspect etait crucial pour mon existence

j'fais des efforts pour me dire que ce que je ressens n'est pas une fatalite mais c'est de plus en plus delicat.. surtout quand je dois jongler avec des parents toxiques.

encore aujourd'hui ma mere a joué provoc 101% quand j'ai craque elle m'a propose de me casser, j'ai donc tout balance y compris la cle

l'ironie c'est que je venais de faire l'effort de faire un cv bidon pour que les boites de jobs alimentaires me selectionne et j'avais pu decrocher un entretien

le taff me plait moyen mais j'me serais motive pour retrouver un equilibre et apaiser les tensions. mais ma mere en a decide autrement et la j'ai encore l'impression de devoir faire ma vie pour fuir les nevroses de mes parents en faisant des choses sans envie et j'commence vraiment a ne plus supporter. ca me lance des douleurs sourdes assez noires. Je peux pas vivre dans le non choix et le mediocre j'ai besoin d'intensite et d'inspiration. Meme a un niveau normal.. un emploi simple peut etre utile (social, ecologique etc).

me voila semi sdf et n'ayant plus rien a faire je regarde si le samu social cherche des gens pour la maraude de ce soir mais c'est deja plein. j'vais quand meme choir sur leur parking et en en rechargeant la page j'vois que c'etait une autre date.

une fois le calme repris et un peu d'empathie envers ma mere qui doit etre a bout pour pleins de raisons aussi, j'envoie un sms pour dire que j'vais aider la nuit et que j'espere qu'elle est plus enervee histoire qu'elle aie pas un probleme de sante plus grave (infarctus sur une crise de nerf). sa reponse dilletante 'je fais a manger, des bonnes blablabla'. La en rentrant elle me reproche de rentrer tard et si j'ai conscience qu'elle est trop fatiguee pour attendre si tard, et qu'elle a fait des pattes.. elle ignore les crises et me tens de la bouffe pour .. je sais pas quoi.. des excuses ? ces cycles se repetent quotidiennement. aggression => nourriture. j'en suis a vomir ce qu'elle met dans les assiettes tellement j'ai l'impression d'avaler sa maladie. j'me sens mort d'avoir capitulé et accepte son petit jeu pervers.

la j'hesite a prendre ce job, une psychiatre parle de centre de repos mais j'ai honte, j'aimerais bien un job debile pour etre au repos tout en etant un peu productif, quitte a etre paye 400e par mois

je suis sec et plus rien ne m'anime de ce que j'etais. si je revois n'importe quoi du passé, 70s, 80s.. qui avaient faisaient resonner des fondements de qui j'etais, une chaleur dans le coeur.. la ca me provoque des 'bleus' a l'arriere du crane.. comme un deuil. c'est vertigineux et insupportable, quand les gens de ton enfance ne te provoquent plus rien, t'as l'impression de ne plus etre, j'ais pas de mot pour traduire ca .. je sais que tout ca a eu lieu mais c'est hors d'atteinte.

j'imaginais que les gens avec une vie normale pouvait conserver ces choses la vivante via les gens avec qui ils ont vecu et grandi. embrasser les proches et revivre les beaux moments un peu

je sais pas si j'peux continuer a avancer au forceps sans vraie fondement humain/existentiel derriere

j'continues a me dire que tenter du mieux c'est la seule voie possible mais j'ai peur de me briser en route

en plus mon corps a l'air desseche, j'ai eu deux semaines de sortes de vertiges, et de somnolences incontrolees (ca c'est souvent signe d'une rechute mais le premier je sais pas)

pour ajouter a la beaute de la situation j'arrive a faire des profits reguliers sur la bourse (je faisais ca en parallele de pole emploi histoire de faire des economies. bonjour le fisc et ses 30%  au passage)..

je regarde la courbe moyenne de profits monter et je suis frigide.. je n'ai personne avec qui le partager, je sais que si j'en parle a ma mere (qui pourtant angoisse sur le manque d'argent [semi imaginaire]) elle va me chier dessus ou alors vouloir me dire que du coup j'peux lui donner pour qu'elle achete un aspirateur (que j'lui ai deja propose de payer 2 fois ..)

je vois les jeunes rire dans la rue .. je n'ai jamais vecu ca

je vois les jeunes flirter insouciants .. je ne vivrais jamais ca j'ai deja depasse le sommet de la colline, je vois l'autre versan

mon compte grandit aussi vite que mon ame s'evapore

je n'ai plus de libido je vis sur l'inertie comme si je pompais mon propre sang

c'est..

* longue pause, peu de progres

  mon corps s'amincit, je suis en tension permanente, je ne reste meme plus chez moi, car je ressens trop de stress

  la colere de mon pere

  son egoisme maladif et la paranoia qui va avec

  toujours a aggresser les gens

  a venir parler de ses envie sur tes plaisirs

  un autisme maladif ?

  doit-on, peut-on pardonner les limites de ses parents ?

  sinon, ma libido morte
  ma jeunesse perdue
  mon incapacite a penser affection et joie en regardant un enfant
  les annees perdues et la montre qui tourne
  la famille detruite et superficielle
  les emotions qui ne viennent plus
  
  ah et la .. la mediocrite du monde

  les gens qui font pas grand chose mais qui se plaignent alors
  qu'ils ont une place sympa

  qui pense que faire une fiche c'est "bosser sur un sujet"

  j'ai plus envie de participer a ce monde nul a chier

  ou tout est masquarade et mise en avant personnelle

  pourtant je pensais etre un mauvais a ce niveau, j'entends les gens pitcher
  leurs projets a la con sur radio je sais pas quoi

  le type est meme pas capable de dire le prix de son truc, il est colle a son
  script comme un mulet

  les autres inventent des termes pour faire joli

  a croire qu'une loi de la nature c'est "qui est le plus apte a mentir et enrober reignera sur le monde"

  et fuyez chercheurs de la verite et de l'harmonie, car vous ne trouverez que la fatigue puis la mort

  Seule surprise: avec le temps doux, s'asseoir lire du Rousseau est agreable.

  C'est bien la premiere fois que je peux lire deux pages sans m'evanouir neurologiquement.

  Tout ce que je veux c'est pouvoir dire haut et fort "j'aime"

  et pas "j'ai pas le choix donc je fais la meme merde que tout le monde" sans joie et ame

  le suicide a l'air plus fun

  -- Autre point, le benevolat

  cette semaine j'me suis mange une lecon d'humanisme trivial, un jeune qui passait a eu le geste juste pendant que nous "benevoles" on attendait comme des cons

  et mes collegues sont soit timbres soit timores soit un peu flous sur leurs buts et motivations

  Peut-etre faut-il de la patience et de la souplesse.

  ps: est-ce que la vie est faite pour reflechir et/ou ruminer ou bien jouer la partition sans sortir du flot ?

* empathetic to my parents but their patterns cause death in me

  mother wants to walk, but she goes away far before me, doing her own thing
  we don't walk, she just goes on her thing alone

  abandonment, betrayl, being used.. my mind rots

* I feel like an angry teenager without the physical hormonal outlet

  the death just rot in me

  old age wisdom kills any value to violence and screaming

  but it's there inside

  i've been destroyed

* j'en peux tellement plus que mon corps lache

  je tiens pas mon rythme de vie
  je mange moins bien

  ma mere me fait chier avec sa facon d'etre de merde de mere poule

  elle va se cacher chez la voisine comme une traitre.

  je sais tres bien que c'est la seule personne normale dans sa vie
  mais elle a meme pas la decence de m'inclure dans sa 'joie'

  elle m'a toujours menti elle ment 99% du temps c'est une fausse
  je la hais physiquement quand elle fait ca et je crains pour sa vie

  j'entends sa voix qui change au telephone, moi elle me parle que de mort et d'angoisse

  elle me detruit des que j'dis un truc ou alors elle fait la maman mais y'a pas de vie
  dans sa voix, c'est juste une gentille posture de gentille mere

  ca me rappelle quand elle a voulu partir. ma mere est une menteuse maladive

  elle n'a jamais su exister, elle m'a laisser mourir et quand j'essaie de vivre elle me sabote
  et la elle recommence a mentir'

  du coup je pars 90% du temps, plus je suis loin mieux c'est

  meme si cette connasse va surement provoquer mon pere dans la cuisine pour se sentir exister

  pas grave si j'en meurs

  j'ai perdu 3 kilos, j'ai mal partout, j'ai le coeur serre (je peux meme plus jogger)

  -- ecouter de la musique remet mon ame dans l'ordre, je me sens serein et j'ai plus de haine
  -- cela dit faut que je parte j'en ai marre de la pesanteur ici
  -- vie morte famille morte sentiments morts.. et rester la c'est vraiment impossible de retrouver
  -- un semblant de normalite (j'ai vraiment essaye beaucoup de choses.. mais tout stagne)

  j'ai passe la nuit en tachychardie, mal de crane .. mains moites, evanoui dans mon lit. bah

  j'ai croise cynthia, elle m'evite du regard..
  c'est sur quand je la croise j'lui parle froidement mais c'est parce que ma vie est
  une immonde merde et j'ai pas envie ni de me faire juger ni de faire chier...
  mais ca fait mal de voir ca.

  je fais des profits sur les marches. voila.

* fin

  saved


    - coupable

    - adolescence mensonge

    - faussete

    - pas de vie

    - pas de personnalite

    - pas de moi

    - depression

    - isolation

    - efforts constants

    - rejection

    - problemes sexuels grave

    - rupture

    - depression morbide

    - aucun soutien

    - moquerie

    - mepris

    - nie

      tu dis nous pour dire toi

      t'es decue de moi alors que face a la mort j'ai fait 1000% d'efforts

      tu ne penses qu'a toi

      meme quand j'essaie d'etre vraiment genereux et altruiste

      tu jettes mes efforts

      tu nies mon existence

      peut-etre que tu te venges d'annees a subir ca

      mais j'ai pas merite

      tu joues la comedie

      t'es une fausse

* therapie 001

  - mensonge

  se forcer a parler
  la politesse
  les faux semblants
  l'amour

- soi

  vivre ce qu'on est, hermite ou pas

- absolu

  chercher ce que l'on desire ou pas

- mensonge parents

  faux semblants ? aggression ou gene ou deception / peine chez eux ?

- amities

  abandon dans la souffrance
  faux semblants
  mais coupable

- perte / enfance

  souvenir effaces

  liens si vivants

- joie

  ne pas mentir, suivre ses instincts me remplissait d'une immense joie

  un desir de vie..

  mais les autres me l'ont vole

  ou du moins le fait de rester a leur contact m'impose des souffrances et
  des limites qui use et on use .. detruit ma joie

  et mon amour aussi.. c'est pour ca que je n'ai plus envie d'etre
  aimant envers ma mere..

  trop de salete et de blessures

  de negligences .. de mensonges

  j'ai des reflexes moribonds, des spasmes d'affections

  qui s'evanouissent aussi vite

- de..?

* rien

  je marche dehors, il fait beau, j'm'asseois dans le parc

  et je ne veux plus les voir

  les gens que j'ai cotoye

  ce sont des souvenirs vide

  mon passe est un souvenir vide

  une plaie ferme

  un membre mort

  je suis bien sans eux mais je ne suis plus

  ce n'est pas la vie que je voulais

  reconcilier et rejoindre mon passe et mon futur

  que faire...

* 41

  - alex me capte dehors

  hier il m'ignore

  aujourd'hui il sort de sa voiture pour me parler

  il est au chomage.. j'hesite mais je cede

  demain on ira marcher ensemble

  aucun soucis mais j'etais quand meme rempli de vide

  c'etait mon pote d'enfance favori durant une petite periode

  periode doree, fin de ma vie normale d'ailleurs

  et la on se parle mais c'est pas sur le meme plan

  c'est plus les liens joyeux d'avant mais juste des discussions

  il a 41 ans, veut partir loin, n'aura pas d'enfants

  il mentionne batignolles

  - je reve de .....

  contrairement a mes reves usuels de filles qui m'echappent

  la elle n'etait pas en train de s'eloigner

  elle m'apportait un truc, pas un signe de retrouvailles

  un truc neutre, on parlait

  j'me suis mis a m'imaginer comment on pourrait et si on devrait
  repasser du temps ensemble.. c'etait doux mais douloureux
  ..

  alex a mentionne batignolles, il a son age .. est-ce que ca a joué ?

  - mediocres dominants et faiblesse

  j'ai ete a mon test phase 2 pour un job

  apres un retard incongru et un demi sprint et quelques blagues

  j'ai rejoin la salle de test

  c'etait un peu dur.. des questions mal enoncees, des signes ambigus

  et voir les gens en charge de l'examen babiller pour justifier de pourquoi
  c'est comme ca et qu'est-ce que ca veut dire

  j'avais envie de partir, mal au ventre de ne pouvoir m'exprimer face
  a tout ce que je deteste

  mais j'ai cede.

  j'ai regarde le mec le moins qualifier reussir a finir a la derniere seconde
  le test topologique

  mais il etait 2eme a finir le test d'assemblage de lego

  les autres n'ont pas fini je crois. etrange.

  - je rentre en passant pres de chez romain

  joli coin du departement, melange quantique d'amitie et de deuil

  dois-je faire ce qui est juste mais injuste

  ou faire ce qui est injuste mais juste

  une fois pres de chez moi ma mere m'appelle

  elle deblatere sans fin je sais pas quoi penser

  pourtant j'etais 80% cool (j'ai ete un peu froid alors que j'avais tort)

  bref pas glorieux

  toujours les memes discussions sur mon manger et ses soit disants efforts
  pour 'avancer'

  
* med

  je perds encore le controle de mes doigts

  mon cerveau a toujours la tete d'une ecchymose

  alerte rouge

* monde

  plat

  'available'

  plus de centralisation, tout le monde est libre de vivre dans sa bulle
  mais comme c'est vite chiant (ostracisme en fait) on cherche a recreer des groupes
  mais a notre guise, donc pas avec l'ancien systeme, avec le nouveau monde decentralise
  discord .. on fait notre petite guilde, secte .. et on invente les regles qui nous font plaisir
  et on refait un monde de petites bulles

  10e qu'on va retomber sur le meme monde qu'avant dans 50 ans

* "maybe i'm wrong" -- quote of the day<AQ11
 
* le samedi soir

  le samedi soir
  tout le monde part
  on voulait pas et on s'met a vouloir
  vouloir faire plus faire durer plus longtemps
  le regret
  de l'instant s'echappant
  revient s'etends

  tout le monde regrette
  les joyeux moments
  mais les fissures s'entassent
  et nous separent
  on s'investi la ou ca glisse
  en se regardant froidement
  quand on se croise

  comment redresser la barre
  d'un navire qui prend l'eau
  ou au moins se dire au revoir
  se rappeler le plus beau

  
* no magnet ?

  induction to power the rotor ?

* souffrance sociale

  tout le monde fait semblant

  tout le monde se gene

  tout le monde manque de quelque chose

  c'est usant

* mauvaise sortie

  - je pensais que reprendre un cdd sans qualif m'aiderait mais pas du tout:

  - j'arrive plus a faire abstraction que je vis avec des gens sans connaissances techniques, ils vivent dans un monde qui me fait mal, tout bricoler et faire sur papier .. dans ma tete j'ai un "leur travail est inutile, ca pourrait etre fait par une gameboy et le pays tournerait mieux"

  - c'est 80% de filles.. ca retourne le couteau dans ma vieille plaie pas fermee

  - je pensais que ca aiderait ma mere a avoir plus d'espace (eviter les problemes avec mon pere) mais en fait non, elle est toujours aussi molle/negative, elle refume

  - j'ai plus trop mal .. mais en fait ca me fait peur, j'ai l'impression d'etre mort vivant .. mon ame ne reponds plus, plus d'envie, plus de desir, plus de rien

  - les taffs de bureaux sont aussi un peu nocif pour moi, ni stimulant mentalement ni physiquement et j'me sens fondre, j'en viens a regretter le benevolat de livraison aux restos du coeur (la bas j'y allais avec de l'entrain meme a 6h du mat.. c'est dire)

  a croire que la societe est un four a evaporer ton ame

  bon c'est une bataille de perdue mais pas la guerre mais je sais meme plus si gagner cette guerre sera une vic

* job vs job

  chaque job est different, meme dans la meme filiere / tache

  bosser dans un ministere a tel lieu ou un autre peut-etre tres different

  dans un plus d'accueil donc aide au secretariat plus importante, et
  c'est un chaos d'interruptions et de taches nulles en petite
  quantite

  en 2h on fait .. rien. 3 fiches et 2 impressions

  dans l'ancien j'etais a l'assistance de gens plus haut place, leur
  taches sont plus regulieres et donc on fait 50 trucs similaires par
  heure, sans interruption ou presque

  par contre l'ancien etait mou et triste (avec des gens qui passent
  leur temps a se chier dessus), le nouveau est plus dynamique

  plus jeunes aussi et la j'me retrouve a jalouser 2 jeunes qui faire
  chauffer leur bouffe ensemble et que je soupconne de tourterer

  je pensais la fille interessee par moi parce qu'elle me parlait en
  dehors des taches de bureau .. l'ironie c'est que je la trouvais pas
  super interessante, tres coquete mais un visage chelou, par contre
  tres tres douce et joviale

  bref je sais pas pourquoi je suis jaloux.. ou alors c'est juste un
  reflexe esthetique

  alors que l'autre fille que j'ai aide etait plus dans ma facon de
  penser et rigolait quand je parlais. pas rigolades genre "t'es un
  blagueur alors je loles" enfin ca avait pas l'air

  par contre comme l'autre lieu (l'ancien ministere) je suis tombe sur
  une lunatique anxieuse qui m'a ghoste en 2 jours.

  cette pute est pas capable de faire son job mais arrive a me chier
  dessus joyeusement comme si elle me dominait .. dinguerie

  j'ai ete attentionné avec elle et je recolte une merde bien puante

  enfin bref .. ce nouveau poste me fatigue un peu du fait de toutes
  ces variables humaines.

  bizarrement une secretaire un peu rude est un peu plus chill, sa
  collegue nerveuse est tres gentille (je la soupconne de grave
  souffrir du manque de cadre face a son inquietude naturelle, surtout
  avec la-dite collegue qui a un sale reflexe de toujours lui rappeler
  qu'elle aurait pas du faire tel truc de telle facon)

  par contre vu que je peux plus tricher en scriptant ni attendre a
  rien foutre comme l'ancien poste .. et que les gens m'inspirent peu,
  je vais devoir trouver une facon de m'amuser

  je suis toujours jaloux et ca m'emmerde et je comprends toujours pas
  c'est chelou

* world dynamics

  le monde n'est-il pas surtout un jeu de vase communicant
  et les limites dans la pyramide sociale domine les futurs possibles

* mathematics pedagogy
  medianes(trices) triangle convergente preuve
  https://www.clayinformatique.ch/mathsenquestions2/wp-content/uploads/2016/02/T.-Droites-remarquables-du-triangle.jpg

  2 cotes A B => mediatrices croisent => point P
  soit droite L passant par P

  Lp (perpendiculaire a L) croise A B une infinite de fois
  Soit I l'intersection de L et Lp
  Soit (LpA)I = I(LpB) et L la mediatrice de LpALpB
  Sinon LpAI et LpBI different
  il suffit de decaler Lp plus pres ou plus loin sur L
  pour atteindre un point d'equilibre ou LpAI = LpBI

  aka une 3eme mediatrice est toujours constructible

  aka les mediatrices convergent en 1 point

* draisienne pliable

  un cadre autour du gars

  pas de barre entre les jambes, il fait le tour de la taille

  tu courres

  et a une vitesse suffisante, tu t'allonges dessus et tu glide

* internet a recree la politique de la vie normale

  peu importe la facon, les interactions d'humains necessitent un cadre
  legal, une structure

  que tout le monde deteste

  mais que tout le monde a provoqué

