
* starting a mind blog

  instead of venting on reddit and IRC and feel abusing others ears
  and eyes, I should publish online. Whoever feels worth spending time
  on these words can do it without me feeling like a self absorbed
  asshole much. I believe writing helps a lot, better thinking,
  diffusing negative emotions.. so I'm gonna do it a bit.

* state of mind @ Sat 30 Jan 2021 09:34:57 AM CET

  I went to a job interview, I was anxious, didn't want to go. It
  failed due to misunderstandings but I felt almost happy for a
  minute.

  What made this ? having a place to go every day ? belonging to a
  group ? being around toys to play with ? (in that case cars).

* i'm tired, my age and mindset relationship

  i have a diploma, some skills, some motivation but at the same time
  I start to not give a fuck about all this. I don't want to chase
  performance, as if my ego is gone. I don't want money much. I want
  stability.. but that may be due to fatigue and lack of control.
  Also I want respect and honest appreciation. I work fast and hard
  whenever I can. I never stop, never waste time. People are slow,
  ranty, unmotivated, or maybe they simply appreciate life
  differently. Maybe my brain is hyperanxious and need stimulation all
  the time. Maybe I don't care about these people and want to drown in
  action to feel happy. A blend of all this.

