#+TITLE: ssss
#+AUTHOR: snekism
#+LANGUAGE: fr
#+EXPORT_FILE_NAME: index.html
#+HTML_HEAD: <link rel="stylesheet" href="https://sandyuraz.com/styles/org.min.css">


* starting a mind blog

  instead of venting on reddit and IRC and feel abusing others ears
  and eyes, I should publish online. Whoever feels worth spending time
  on these words can do it without me feeling like a self absorbed
  asshole much. I believe writing helps a lot, better thinking,
  diffusing negative emotions.. so I'm gonna do it a bit.

* state of mind @ Sat 30 Jan 2021 09:34:57 AM CET

  I went to a job interview, I was anxious, didn't want to go. It
  failed due to misunderstandings but I felt almost happy for a
  minute.

  What made this ? having a place to go every day ? belonging to a
  group ? being around toys to play with ? (in that case cars).

* i'm tired, my age and mindset relationship

  i have a diploma, some skills, some motivation but at the same time
  I start to not give a fuck about all this. I don't want to chase
  performance, as if my ego is gone. I don't want money much. I want
  stability.. but that may be due to fatigue and lack of control.
  Also I want respect and honest appreciation. I work fast and hard
  whenever I can. I never stop, never waste time. People are slow,
  ranty, unmotivated, or maybe they simply appreciate life
  differently. Maybe my brain is hyperanxious and need stimulation all
  the time. Maybe I don't care about these people and want to drown in
  action to feel happy. A blend of all this.

* github.io activated

  spent 10 minutes setting up github as host for this.  felt real
  boring but alas.. I wonder if people are paid for these tasks
  sometimes, probably. Not important.

* situations at the house not better

  father is really overwhelming, cranky and heavy.. the more a
  situation goes bad, the worst he becomes. Tension makes him more
  tense. Nothing surprising.

  My mother talks about him as a thing. In front of me.. makes me mad.

  It's still a rotting pot of anger. You know where every move sounds
  angry. A door close for no reason, a drawer shut too fast. Dishes
  dropped loudly.

  I should write a note and leave. If I wasn't afraid my parents
  wouldn't go violent I'd do so. I guess that's exactly the problem in
  these kind of situations.. you don't move because it's a lose-lose
  situation with potentially critical consequences.

  Maybe I should talk to people and find support.
  
* work - volunteering

  I like volunteering at the food charity. My tasks are basic. The
  rhythm is average. People are not in a rush either.  Some would say
  they're a charity so obviously they're not in a hurry, but truth is
  that most private places I went to weren't faster. Only people
  dealing with high rates of clients (restaurants, trains) have hard
  rhythm constraints. Oh and high production rate factories. But I
  like that.. I don't know why people hate going fast on repetitive
  gestures. To me it's like converging toward perfection and then
  keeping there for 4 hours. A high zen experience. I'd understand for
  physical labour done wrong.. nobody wants to carry 10 tons of stuff
  for 4 hours. But even unpacking lots of food can be fun. You just
  have to organize yourself to find the easiest and fastest
  configuration. Then it becomes a pleasure. Truth is people don't do
  this because 1) education (as a programmer I became used to seek
  every wasted second) 2) petty revenge due to feud with hierarchy or
  other people. Why work fast if your boss talks down to
  you.. respect/care/affection is such a big factor in how we work. A
  good king could make a whole nation work twice better just by his
  appreciation only.

* redinho waste

  https://completemusicupdate.com/wp-content/uploads/2017/10/tomcalvertzanbor1250.jpg

  | https://imgur.com/a/u9ZhXeZ  |
  |------------------------------|
  | https://archive.is/wip/hamjV |

  see this pic. a busted synth.. parts out in the open, internals
  exposed, design off.

  that thing was an epic item in the 90s, high valued device or toy,
  for a high valued art form gone semi-mainstream.

  but it was fabricated.. yet it's not what it was important for, it's
  that glow from how it looks and convey it's use and
  capabilities. how you feel and interact with it. how it embodies the
  desires and factors of an era.

  something that I consider timeless and more important than the
  current thinking about innovation. especially the immaterial side of
  new tech.
  
* phases and big picture

  few years earlier i was a slacker, illegal streaming and porn was my
  daily life, sleeping the day.. life felt like shit but nothing near
  close to how heavy, difficult and painful it is now. The irony is
  that I do 100x more..


  
* era of simulacre

  we're being sold that more data, more pics, more pixels is
  better. these were side bonuses of a good life, having good times
  and enough more to buy a camera, but the camera means nothing. old
  fading 70s pics, blurry pics .. photo albums with 10 .. have more
  worth than my google photo account filled with 1000s of superb (not
  really) shots of my lonely sad self.

* inotify upload

  ```inotifywait -q -m -e CLOSE_WRITE --format="git commit -m 'auto
  commit' %w && git push origin <<branch>>" <<file>> | bash```

* to drop or not to drop

  Apres la tension et la douleur des derniers jours, je me sens
  vide. J'ai plus la reponse anxieuse qui me fait vouloir
  lutter.. j'abandonne mes parents a leur misere et je vais finir ma
  vie tristement un peu plus loin.

  La culpabilite me detruit toujours. Et c'est normal.

  Suis-je le seul responsable..

  00
