#+TITLE: ssss
#+AUTHOR: snekism
#+LANGUAGE: fr
#+EXPORT_FILE_NAME: index.html
#+HTML_HEAD: <link rel="stylesheet" href="https://sandyuraz.com/styles/org.min.css">


* starting a mind blog

  instead of venting on reddit and IRC and feel abusing others ears
  and eyes, I should publish online. Whoever feels worth spending time
  on these words can do it without me feeling like a self absorbed
  asshole much. I believe writing helps a lot, better thinking,
  diffusing negative emotions.. so I'm gonna do it a bit.

* state of mind @ Sat 30 Jan 2021 09:34:57 AM CET

  I went to a job interview, I was anxious, didn't want to go. It
  failed due to misunderstandings but I felt almost happy for a
  minute.

  What made this ? having a place to go every day ? belonging to a
  group ? being around toys to play with ? (in that case cars).

* i'm tired, my age and mindset relationship

  i have a diploma, some skills, some motivation but at the same time
  I start to not give a fuck about all this. I don't want to chase
  performance, as if my ego is gone. I don't want money much. I want
  stability.. but that may be due to fatigue and lack of control.
  Also I want respect and honest appreciation. I work fast and hard
  whenever I can. I never stop, never waste time. People are slow,
  ranty, unmotivated, or maybe they simply appreciate life
  differently. Maybe my brain is hyperanxious and need stimulation all
  the time. Maybe I don't care about these people and want to drown in
  action to feel happy. A blend of all this.

* github.io activated

  spent 10 minutes setting up github as host for this.  felt real
  boring but alas.. I wonder if people are paid for these tasks
  sometimes, probably. Not important.

* situations at the house not better

  father is really overwhelming, cranky and heavy.. the more a
  situation goes bad, the worst he becomes. Tension makes him more
  tense. Nothing surprising.

  My mother talks about him as a thing. In front of me.. makes me mad.

  It's still a rotting pot of anger. You know where every move sounds
  angry. A door close for no reason, a drawer shut too fast. Dishes
  dropped loudly.

  I should write a note and leave. If I wasn't afraid my parents
  wouldn't go violent I'd do so. I guess that's exactly the problem in
  these kind of situations.. you don't move because it's a lose-lose
  situation with potentially critical consequences.

  Maybe I should talk to people and find support.

* work - volunteering

  I like volunteering at the food charity. My tasks are basic. The
  rhythm is average. People are not in a rush either.  Some would say
  they're a charity so obviously they're not in a hurry, but truth is
  that most private places I went to weren't faster. Only people
  dealing with high rates of clients (restaurants, trains) have hard
  rhythm constraints. Oh and high production rate factories. But I
  like that.. I don't know why people hate going fast on repetitive
  gestures. To me it's like converging toward perfection and then
  keeping there for 4 hours. A high zen experience. I'd understand for
  physical labour done wrong.. nobody wants to carry 10 tons of stuff
  for 4 hours. But even unpacking lots of food can be fun. You just
  have to organize yourself to find the easiest and fastest
  configuration. Then it becomes a pleasure. Truth is people don't do
  this because 1) education (as a programmer I became used to seek
  every wasted second) 2) petty revenge due to feud with hierarchy or
  other people. Why work fast if your boss talks down to
  you.. respect/care/affection is such a big factor in how we work. A
  good king could make a whole nation work twice better just by his
  appreciation only.

* redinho waste

  https://completemusicupdate.com/wp-content/uploads/2017/10/tomcalvertzanbor1250.jpg

  | https://imgur.com/a/u9ZhXeZ  |
  |------------------------------|
  | https://archive.is/wip/hamjV |

  see this pic. a busted synth.. parts out in the open, internals
  exposed, design off.

  that thing was an epic item in the 90s, high valued device or toy,
  for a high valued art form gone semi-mainstream.

  but it was fabricated.. yet it's not what it was important for, it's
  that glow from how it looks and convey it's use and
  capabilities. how you feel and interact with it. how it embodies the
  desires and factors of an era.

  something that I consider timeless and more important than the
  current thinking about innovation. especially the immaterial side of
  new tech.

* phases and big picture

  few years earlier i was a slacker, illegal streaming and porn was my
  daily life, sleeping the day.. life felt like shit but nothing near
  close to how heavy, difficult and painful it is now. The irony is
  that I do 100x more..



* era of simulacre

  we're being sold that more data, more pics, more pixels is
  better. these were side bonuses of a good life, having good times
  and enough more to buy a camera, but the camera means nothing. old
  fading 70s pics, blurry pics .. photo albums with 10 .. have more
  worth than my google photo account filled with 1000s of superb (not
  really) shots of my lonely sad self.

* inotify upload

  ```inotifywait -q -m -e CLOSE_WRITE --format="git commit -m 'auto
  commit' %w && git push origin <<branch>>" <<file>> | bash```

* to drop or not to drop

  Apres la tension et la douleur des derniers jours, je me sens
  vide. J'ai plus la reponse anxieuse qui me fait vouloir
  lutter.. j'abandonne mes parents a leur misere et je vais finir ma
  vie tristement un peu plus loin.

  La culpabilite me detruit toujours. Et c'est normal.

  Suis-je le seul responsable..

  --


* recovery

  is it possible I recover to a normal state of existence ? my
  childhood feels dead, I have no people around I love, only ghosts
  with whom I have painful feelings, who are hurting me a lot, who
  never made me feel me .. nobody knows me. not surprising, I couldn't
  speak before, but now I do nobody listens. it's horrible, my truth,
  my soul is dust in the wind.

* trading sucks and doesn't

  trading is a soulless game where someone gives you his money so he
  can wait to later be in profit or not.

  most of the trading is superstitiously weak science (averages
  averages averages fib series averages)

  but it has some general life lessons:

  - follow others for a while
    benefits are easier

  - don't follow others (sic)
    when they go insane. the system lives on the mean. that's where
    things are stable

  - be patient
    timing is key, too early you lose, too late you lose

  - be cautious
    you lose if you stop prepping for problems

  - cycles everywhere

  - learn how to get into chaos without being foolish

    you have to tame fear, thus design plans to deal with all outcomes

  -

* sour pain, deep and wide, silence

  i want to leave 'these persons' away.. i only feel happy when I
  picture myself with others, I have remains of life in me, but I
  can't express it with them.

  part of it is the years of sadness in this house

  part of it is the guilt of my maybe crime

  part of it is .. i forgot. I shouldn't be editing text while I
  listen to aerosmith.

  since my breakup I have this feeling that interacting with people is
  different, i need to be heard, i need genuine contact and honesty
  and connection

  it's a critical need

  and every time I talk to my parents.. there's no such things, it's
  fake, twisted, or silence

  that's why I want them out.

  they provided a roof.. but I can make a roof, it's not what I need

  I scream in my head since i'm in college, nightmares and now pure
  pain.

  future looks bleak, i'm thinking of offing myself because I can't
  deal with more grief, i cant kill them from my head either tbh.. but
  it doesn't evolve well

  I assume that's what people feel when marriage/couple doesn't work
  and the other party cannot listen or make an effort.

  Sometimes I want to scream, sing, make music to let the pain out,
  the life out. But if feels so weak and so worthless now..

  even anger or breaking things seems moot, I felt utterly defeated at
  the store today.. a whole 20 years of life gone. vapor. Actually
  that's a cute image. Even this whole failure is not nothing.. it
  became vapor.

  it's like i never lived, my impulses are gone, my desires are gone,
  there's no blood

  yet i have this void and this need to have some.. to have been

  it hurts.

  This is why I want to harm my mother(and father too) I think somehow
  they deprived me of that. They never wanted to see me alive.. any
  time I try I get shit or hurdles from them.

  falling on your face is bliss

  it mean you tried

* dignity and life

  forgot.

* irc

  175

  <snek76`> damn I had to drop my mother at the car shop [18:24] |
<snek76`> every second next to her is a death sentence of anxiety |
<snek76`> "i need to leave" | <snek76`> she exudes stress nearby her
own son | <snek76`> she claim she 'loves' me all the fuckin time |
<snek76`> but she uses me as a prop | <snek76`> makes me very violent
[18:25] | ERC>


* elders

  most of my mother family is annoying, sad, sick.

  not interesting, rambling, judging, drinking

  I want to tell them to go fuck off

  But I feel dirty. I think I can't disrespect them. I think it's
  sacred. Roots you shall not break.

* life

  why am i stuck ? cause I didn't have the possibilty of living. I
  couldn't make friends, i faked my existence mostly .. it ended
  nowhere

  then i had that girl it was eye opening.. but i lost her

  and even though i could work, i always could since i was a 6yo..

  i need friends, human relationships .. not contractual ones for
  money

  i dont want to perform, to get customers.. it's devoid of meaning
  and makes me suicidal at times

  i help for free at the charity.. free. i don't care about money

  people never hear me, never listen, never understand..


* importance

  some stuff have more value than others

  i'm 40. i try not to mind about the figure but it's dramatic, i feel
  in pain most of my time, memories are fading, and these are actually
  the only thing I care about.. anything 'good' I can do now is mostly
  damage control / me-too revenge. I don't care about being successful
  or making money, I'd rejoy a lot more in the warmth of old friends
  and family but i broke that.

  maybe i over analyze my role into this but still if our lives were
  driven around preserving these I think a lot of us would be happier.

  I see tearful eyes when I ran into people I knew. They miss the days
  too.. they walk with the burden of the void.

* self talk

  I ramble about me all the time

* reconnect forget forgive confess

  can i reconnect with people around ?

  without telling the truth ?

  i don't think so

  it's a lose lose situation

* when you can't cry anymore

  Confused and painful life to that point is hard to deal. it's a sad
  kind of grief.

  I wasn't able to live before, and i messed up, and now i'm guilty
  and i can 'live' but i'm guilty so I cannot life in joy and peace
  because morally it's wrong, and morales and humanity is exactly what
  I just got.

  I despise.. or hate people that were around me at the time. They
  didn't help.. are you responsible.. not really. But I expect them to
  blame me fully when they'll know. Unfair. I wasn't capable of
  dealing with these things. Honestly something was not there in my
  brain. Oh well I could have but I was weak.. having a gf and feeling
  love just made me stronger and opened my eyes to responsibilty.

  I'll have to confess. I'll die because of it but I'll die human.

* shrink limits - hate - grief

  new therapist is talkative, it helps a lot for me, silence is not
  what i need, there's plenty of silence in my own room or car.

  i cannot discuss everything i really need to, she still thinks
  moving out is the best course of action.. it's a delicate matter.

  moving signals this family is officially sick. my desire was to have
  just enough time to find a simple job, live a bit, find a
  flat.. evolve swiftly but organically.

  parents are not letting this happen

  now with that therapist i am a bit neutral but whenever i'm home i
  become sad and suffering again.


* ground to nothing

  i lived 30 years following others, accepting in secret what i didn't
  want to

  this girl unlocked my self esteem

  but also made me subject to deep wounds whenever people did
  something wrong in my views

  to avoid harming others with verbal rage i .. killed myself

  i hate most people around me

  they're weak, lame, sad, liars, abusers, rapists, fake, ignorants,
  limited, dishonest

  i want them all of my sight.. well i wanted, i should have send them
  to fuck off clearly, just so once in my life, when i need to exist,
  to have my voice and my soul heard out loud and clear

  i didnt

  and now this energy of life left me

  i left my own body.

  it feels like a bruise in my brain, not even trying to paint a
  picture, it does actually hurt(something odd since brain has no
  nociception in theory)

  in a way i would have hurt some people physically because i hate
  them so much

  but i would have been free and alive I assume.

  it's difficult to deal with so many extinctions of the self.

* blips of joy

  i'm still guilty, still angry, still violent, still hateful

  want to get rid of everybody in my head

  yet 5 minutes ago I had that feeling of friendship and people i used
  to know with a good 'hi friend what are you doing ?' with a normal
  feeling of affection and fun.

  i don't know what's what.. i don't know what to feel or trust.

  so weird

  I want to cry because I feel nothing or don't love my relatives.

  maybe i'm still fucked up from grieving.

  but everytime my mother closes a door, or talks about death

  the suffering comes back

  i hate her

  i hate her fucked up brain u_u;


  ... even writing this is useless, but I guess I cannot be heard nor
  taken into account. They're all wrong and they're killing me without
  caring. Shrink thinks I should talk to them more but why.. they
  never understand, and keep doing it. hhhaa

* what to do.

  I keep having memories of 'friends' i somehow hate.  Two things, I
  wasn't happy at that time, and I did them wrong.  The childhood
  memory that would have been a reason to forgive and evolve with them
  a bit, as normal friend would do, is bruised and painful like my ex
  memories. Since I had to kill her from my head.. I can kill anybody
  from my head that makes me suffer.  It's inhuman.

  Same for my parents, they're here but we don't talk.. I want to fix
  the situation in theory.. but these are not my 'parents'.. these are
  people that used to be my parents. People that would be somehow
  empathetic to me.. I'm not screaming to my needs only, even when I
  try to do good for all of us.. they cause me pain.

  I should confess.. but it's a terminal loss loss situation.

  Maybe I should consult a doctor.

  oh, and right now I'm making money on speculation, i'm literally a
  cliché of the sad guy. +1 cents every day, and -1 friend every
  day. No balance.


* death

  they ignored my suffering when i was silent

  they ignored my suffering when i was vocal

  they ignored my wounds, my injuries and made me suffer more for
  their petty needs

  supporting their manias or violence, my mother going insane over
  details on her mother's grave

  they harm me emotionally on a regular basis

  sometime they even claim they want to forget me

  i was doing great things, recovering cleanly, working nicely, being
  healthy

* reality is relative to short / long term understanding

  kinda like .. spacetime.. every local spot has its own reality due
  to ignorance of further away what's "happens" in the near time has
  no real bearing on what is true or real things that are true now may
  just appear true because they hold

  due to whatever temporary reasons

  even though quite later they'll fail and be replaced by the opposite

* depression is void of emotional memory

  you remember good
  you want more
  you happy
  you go for the same good things again

  depression robs this ?

  the memory isn't there, is contradicted by other memories

  you have nothing to seek

  @see-lower: friendship also responds to this principle. other people
  share, represent, incarnate, revives these memories. keep that
  something alive

* like a stranger

  i look at my father, his family, his life, the music

  the memories

  they're faded but not sour.. not grief. yet my father is still there
  but it's in me.

  I'm a bit sad it's over, it was nice in a way.

  we can't talk.. we never did. i wonder if he's hurt by the silence,
  the pain..

  i don't want to break it further.. i'll find a job,

  i would already have done so if my parents weren't so
  difficult.. but i'll make more steps.

  i cannot violate this.  * internet is too much
